import Database from 'better-sqlite3'

interface ItemUpdate {
  name: string
  attributes: string
}

interface ItemDelete {
  name: string
}

const itemsToDelete: ItemDelete[] = [
  { name: 'Media justicia: oscura' },
  { name: 'horas-de-basura' },
  { name: '__Mizutsune__' },
  { name: '__Ave elemental legendaria__' },
  { name: 'Bouquete de flores' },
  { name: 'Trombón' },
  { name: 'hada' },
  { name: 'raton' },
  { name: 'cronoataud' },
  { name: 'patocapa' },
  { name: 'correa del perrito' },
  { name: 'trofeo de caza' },
  { name: 'buho' },
  { name: 'Vial Lumínico' },
  { name: 'token parry berserk' },
  { name: 'gato' },
  { name: 'llave lootbox' },
  { name: 'token aegis' },
  { name: 'aguila' },
  { name: 'omnivial' },
  { name: 'perro' },
  { name: 'tortuga' },
  { name: 'rana' },
  { name: 'z latigo divino' },
  { name: 'z latigo oscuro' },
  { name: '**Puntos de Amistad**' },
  { name: '<:BanHammer:505714059652366337>' },
  { name: 'Cofre de Oro' },
  { name: 'cofre semanal' },
]

const itemsToUpdate: ItemUpdate[] = [
  // Items 1-50
  { name: 'Espada de madera', attributes: 'ataque+1d4' },
  { name: 'Varita de principiante', attributes: 'ataque_magico+1d4' },
  { name: 'Escudo de madera', attributes: 'defensa+1d4' },
  { name: 'Casco de cuero', attributes: 'armadura+2' },
  { name: 'daga normal', attributes: 'ataque+1d3' },
  { name: 'espada normal', attributes: 'ataque+1d6' },
  { name: 'escudo normal', attributes: 'defensa+1d6' },
  { name: 'armadura cuero', attributes: 'armadura+6, nulimagia+4' },
  { name: 'Espada de hierro', attributes: 'ataque+1d7' },
  { name: 'Espada larga de hierro', attributes: 'ataque+1d8' },
  { name: 'Hacha de hierro', attributes: 'ataque+1d9' },
  { name: 'Gran hacha de hierro', attributes: 'ataque+2d6' },
  { name: 'Espada de plata', attributes: 'ataque+1d8' },
  { name: 'Espada larga de plata', attributes: 'ataque+1d9' },
  { name: 'Armadura de placas', attributes: 'armadura+12, nulimagia+8' },
  { name: 'Armadura de cuero endurecido', attributes: 'armadura+8, nulimagia+6' },
  { name: 'Armadura de placas de hierro', attributes: 'armadura+15, nulimagia+10' },
  { name: 'Armadura completa de hierro', attributes: 'armadura+18, nulimagia+12' },
  { name: 'Armadura de placas de plata', attributes: 'armadura+18, nulimagia+15' },
  { name: 'Espada de acero', attributes: 'ataque+1d9' },
  { name: 'Espada larga de acero', attributes: 'ataque+1d10' },
  { name: 'Gran espada de acero', attributes: 'ataque+2d7' },
  { name: 'Hacha de acero', attributes: 'ataque+1d10' },
  { name: 'Gran hacha de acero', attributes: 'ataque+2d8' },
  { name: 'Armadura de acero', attributes: 'armadura+20, nulimagia+15' },
  { name: 'Armadura completa de acero', attributes: 'armadura+22, nulimagia+18' },
  { name: 'Ballesta ligera', attributes: 'ataque+1d8' },
  { name: 'Ballesta pesada', attributes: 'ataque+2d6' },
  { name: 'Arco largo', attributes: 'ataque+1d8' },
  { name: 'Arco compuesto', attributes: 'ataque+1d10' },
  { name: 'Arco corto', attributes: 'ataque+1d6' },
  { name: 'Cetro de principiante', attributes: 'ataque_magico+1d4, mana+3' },
  { name: 'Cetro de aprendiz', attributes: 'ataque_magico+1d6, mana+5' },
  { name: 'Cetro de mago', attributes: 'ataque_magico+1d8, mana+7' },
  { name: 'Cetro de archimago', attributes: 'ataque_magico+1d10, mana+10' },
  { name: 'Túnica de mago', attributes: 'armadura+5, nulimagia+8, mana+3' },
  { name: 'Túnica de archimago', attributes: 'armadura+8, nulimagia+12, mana+5' },
  { name: 'Bastón de principiante', attributes: 'ataque_magico+1d4, mana+4' },
  { name: 'Bastón de druida', attributes: 'ataque_magico+1d6, mana+6' },
  { name: 'Armadura de cuero tachonado', attributes: 'armadura+10, nulimagia+6' },
  { name: 'Gran escudo de acero', attributes: 'defensa+1d10' },
  { name: 'Gran escudo de hierro', attributes: 'defensa+1d8' },
  { name: 'Escudo de acero', attributes: 'defensa+1d8' },
  { name: 'Daga de plata', attributes: 'ataque+1d4' },
  { name: 'Daga de acero', attributes: 'ataque+1d5' },
  { name: 'Daga de hierro', attributes: 'ataque+1d3' },
  { name: 'Hacha de plata', attributes: 'ataque+1d8' },
  { name: 'Gran hacha de plata', attributes: 'ataque+2d7' },
  { name: 'Mazo de hierro', attributes: 'ataque+1d8' },
  { name: 'Gran mazo de hierro', attributes: 'ataque+2d6' },
  // Items 51-100
  { name: 'Maza de acero', attributes: 'ataque+1d8' },
  { name: 'Gran maza de acero', attributes: 'ataque+2d7' },
  { name: 'Martillo de guerra', attributes: 'ataque+1d10' },
  { name: 'Martillo de guerra pesado', attributes: 'ataque+2d8' },
  { name: 'Lanza de madera', attributes: 'ataque+1d6' },
  { name: 'Lanza de hierro', attributes: 'ataque+1d8' },
  { name: 'Lanza de acero', attributes: 'ataque+1d10' },
  { name: 'Alabarda de hierro', attributes: 'ataque+1d9' },
  { name: 'Alabarda de acero', attributes: 'ataque+1d11' },
  { name: 'Hoz de hierro', attributes: 'ataque+1d6' },
  { name: 'Hacha arrojadiza', attributes: 'ataque+1d6' },
  { name: 'Cuchillo arrojadizo', attributes: 'ataque+1d4' },
  { name: 'Jabalina de hierro', attributes: 'ataque+1d7' },
  { name: 'Guanteletes de hierro', attributes: 'armadura+5, nulimagia+2' },
  { name: 'Guanteletes de acero', attributes: 'armadura+7, nulimagia+4' },
  { name: 'Botas de hierro', attributes: 'armadura+5, nulimagia+2' },
  { name: 'Botas de acero', attributes: 'armadura+7, nulimagia+4' },
  { name: 'Casco de hierro', attributes: 'armadura+5, nulimagia+2' },
  { name: 'Casco de acero', attributes: 'armadura+7, nulimagia+4' },
  { name: 'Espada bastarda', attributes: 'ataque+1d10' },
  { name: 'Espada de dos manos', attributes: 'ataque+2d7' },
  { name: 'Cimitarra de acero', attributes: 'ataque+1d8' },
  { name: 'Sable de acero', attributes: 'ataque+1d9' },
  { name: 'Katana de acero', attributes: 'ataque+1d10' },
  { name: 'Nodachi de acero', attributes: 'ataque+2d7' },
  { name: 'Dai-katana', attributes: 'ataque+1d12' },
  { name: 'Wakizashi de acero', attributes: 'ataque+1d6' },
  { name: 'Tanto de acero', attributes: 'ataque+1d4' },
  { name: 'Arco largo compuesto', attributes: 'ataque+1d10' },
  { name: 'Arco de caza', attributes: 'ataque+1d8' },
  { name: 'Ballesta de repeticion', attributes: 'ataque+1d9' },
  { name: 'Ballesta de precision', attributes: 'ataque+2d6' },
  { name: 'Revolver de plomo', attributes: 'ataque+1d6' },
  { name: 'Pistola de plomo', attributes: 'ataque+1d6' },
  { name: 'Mosquete de plomo', attributes: 'ataque+1d10' },
  { name: 'Rifle de plomo', attributes: 'ataque+1d12' },
  { name: 'Escopeta de plomo', attributes: 'ataque+2d6' },
  { name: 'Baston de mago', attributes: 'ataque_magico+1d8, mana+8' },
  { name: 'Baston de archimago', attributes: 'ataque_magico+1d10, mana+12' },
  { name: 'Varita de mago', attributes: 'ataque_magico+1d6, mana+5' },
  { name: 'Varita de archimago', attributes: 'ataque_magico+1d8, mana+8' },
  { name: 'Grimorio de principiante', attributes: 'mana+3' },
  { name: 'Grimorio de mago', attributes: 'mana+6' },
  { name: 'Grimorio de archimago', attributes: 'mana+10' },
  { name: 'Anillo de mana', attributes: 'mana+3' },
  { name: 'Anillo de mana mayor', attributes: 'mana+5' },
  { name: 'Amuleto de mana', attributes: 'mana+4' },
  { name: 'Amuleto de mana mayor', attributes: 'mana+7' },
  { name: 'Capa de mago', attributes: 'armadura+3, nulimagia+5, mana+2' },
  { name: 'Capa de archimago', attributes: 'armadura+5, nulimagia+8, mana+4' },
  // Items 101-150
  { name: 'Sombrero de mago', attributes: 'armadura+2, nulimagia+4, mana+2' },
  { name: 'Sombrero de archimago', attributes: 'armadura+4, nulimagia+6, mana+4' },
  { name: 'Botas de mago', attributes: 'armadura+2, nulimagia+3, mana+1' },
  { name: 'Botas de archimago', attributes: 'armadura+3, nulimagia+5, mana+2' },
  { name: 'Guantes de mago', attributes: 'armadura+2, nulimagia+3, mana+1' },
  { name: 'Guantes de archimago', attributes: 'armadura+3, nulimagia+5, mana+2' },
  { name: 'Armadura de cuero ligero', attributes: 'armadura+4, nulimagia+3' },
  { name: 'Armadura de cuero reforzado', attributes: 'armadura+8, nulimagia+5' },
  { name: 'Armadura de malla', attributes: 'armadura+12, nulimagia+6' },
  { name: 'Armadura de malla completa', attributes: 'armadura+16, nulimagia+10' },
  { name: 'Armadura de placas completa', attributes: 'armadura+25, nulimagia+18' },
  { name: 'Armadura de obsidiana', attributes: 'armadura+30, nulimagia+25' },
  { name: 'Escudo de obsidiana', attributes: 'defensa+1d12' },
  { name: 'Espada de obsidiana', attributes: 'ataque+1d12' },
  { name: 'Hacha de obsidiana', attributes: 'ataque+1d13' },
  { name: 'Maza de obsidiana', attributes: 'ataque+1d11' },
  { name: 'Lanza de obsidiana', attributes: 'ataque+1d11' },
  { name: 'Daga de obsidiana', attributes: 'ataque+1d6' },
  { name: 'Casco de obsidiana', attributes: 'armadura+8, nulimagia+6' },
  { name: 'Guanteletes de obsidiana', attributes: 'armadura+8, nulimagia+6' },
  { name: 'Botas de obsidiana', attributes: 'armadura+8, nulimagia+6' },
  { name: 'Capa de obsidiana', attributes: 'armadura+6, nulimagia+8' },
  { name: 'espada de la reina', attributes: 'ataque+1d14' },
  { name: 'armadura de la reyna', attributes: 'armadura+20, nulimagia+25, mana+4' },
  { name: 'corona de la reyna', attributes: 'armadura+8, nulimagia+8, mana+3' },
  { name: 'armadura oscura', attributes: 'armadura+22, nulimagia+18' },
  { name: 'espada oscura', attributes: 'ataque+1d11' },
  { name: 'armadura pesada oscura', attributes: 'armadura+28, nulimagia+20' },
  { name: 'espada pesada oscura', attributes: 'ataque+2d8' },
  { name: 'Armadura completa oscura', attributes: 'armadura+35, nulimagia+28' },
  { name: 'daga oscura', attributes: 'ataque+1d5' },
  { name: 'hacha oscura', attributes: 'ataque+1d11' },
  { name: 'gran hacha oscura', attributes: 'ataque+2d8' },
  { name: 'maza pesada oscura', attributes: 'ataque+2d7' },
  { name: 'armadura de asesino', attributes: 'armadura+10, nulimagia+10' },
  { name: 'espada de asesino', attributes: 'ataque+1d8' },
  { name: 'daga de asesino', attributes: 'ataque+1d6' },
  { name: 'armadura de cazador', attributes: 'armadura+10, nulimagia+8' },
  { name: 'arco de cazador', attributes: 'ataque+1d10' },
  { name: 'espada cazadora', attributes: 'ataque+1d9' },
  { name: 'ballesta de cazador', attributes: 'ataque+1d10' },
  { name: 'daga de cazador', attributes: 'ataque+1d5' },
  { name: 'hacha de cazador', attributes: 'ataque+1d8' },
  { name: 'armadura de guardian', attributes: 'armadura+15, nulimagia+10' },
  { name: 'escudo de guardian', attributes: 'defensa+1d10' },
  { name: 'espada de guardian', attributes: 'ataque+1d9' },
  { name: 'lanza de guardian', attributes: 'ataque+1d9' },
  { name: 'mazo de guardian', attributes: 'ataque+1d10' },
  { name: 'armadura sagrada', attributes: 'armadura+25, nulimagia+30' },
  { name: 'espada sagrada', attributes: 'ataque+1d12' },
  // Items 151-200
  { name: 'escudo sagrado', attributes: 'defensa+1d10' },
  { name: 'casco sagrado', attributes: 'armadura+8, nulimagia+10' },
  { name: 'guanteletes sagrados', attributes: 'armadura+8, nulimagia+10' },
  { name: 'botas sagradas', attributes: 'armadura+8, nulimagia+10' },
  { name: 'capa sagrada', attributes: 'armadura+6, nulimagia+10, mana+3' },
  { name: 'armadura de titan', attributes: 'armadura+40, nulimagia+30' },
  { name: 'espada de titan', attributes: 'ataque+2d10' },
  { name: 'escudo de titan', attributes: 'defensa+1d14' },
  { name: 'casco de titan', attributes: 'armadura+12, nulimagia+8' },
  { name: 'guanteletes de titan', attributes: 'armadura+12, nulimagia+8' },
  { name: 'botas de titan', attributes: 'armadura+12, nulimagia+8' },
  { name: 'armadura de dragon', attributes: 'armadura+35, nulimagia+25' },
  { name: 'espada de dragon', attributes: 'ataque+1d14' },
  { name: 'escudo de dragon', attributes: 'defensa+1d12' },
  { name: 'casco de dragon', attributes: 'armadura+10, nulimagia+8' },
  { name: 'guanteletes de dragon', attributes: 'armadura+10, nulimagia+8' },
  { name: 'botas de dragon', attributes: 'armadura+10, nulimagia+8' },
  { name: 'Armadura de dragon rojo', attributes: 'armadura+35, nulimagia+25' },
  { name: 'Armadura de dragon negro', attributes: 'armadura+38, nulimagia+30' },
  { name: 'espada de dragon rojo', attributes: 'ataque+1d14' },
  { name: 'espada de dragon negro', attributes: 'ataque+1d16' },
  { name: 'arco de dragon', attributes: 'ataque+1d12' },
  { name: 'ballesta de dragon', attributes: 'ataque+1d12' },
  { name: 'hacha de dragon', attributes: 'ataque+1d13' },
  { name: 'lanza de dragon', attributes: 'ataque+1d12' },
  { name: 'daga de dragon', attributes: 'ataque+1d7' },
  { name: 'mazo de dragon', attributes: 'ataque+1d12' },
  { name: 'cetro de dragon', attributes: 'ataque_magico+1d10, mana+8' },
  { name: 'armadura de dragon dorado', attributes: 'armadura+42, nulimagia+35' },
  { name: 'espada de dragon dorado', attributes: 'ataque+1d16' },
  { name: 'escudo de dragon dorado', attributes: 'defensa+1d14' },
  { name: 'guanteletes de dragon dorado', attributes: 'armadura+12, nulimagia+10' },
  { name: 'botas de dragon dorado', attributes: 'armadura+12, nulimagia+10' },
  { name: 'casco de dragon dorado', attributes: 'armadura+12, nulimagia+10' },
  { name: 'armadura de angel', attributes: 'armadura+20, nulimagia+25, mana+5' },
  { name: 'espada de angel', attributes: 'ataque+1d12' },
  { name: 'arco de angel', attributes: 'ataque+1d11' },
  { name: 'escudo de angel', attributes: 'defensa+1d10' },
  { name: 'casco de angel', attributes: 'armadura+8, nulimagia+10, mana+3' },
  { name: 'guanteletes de angel', attributes: 'armadura+8, nulimagia+10, mana+3' },
  { name: 'botas de angel', attributes: 'armadura+8, nulimagia+10, mana+3' },
  { name: 'capa de angel', attributes: 'armadura+6, nulimagia+10, mana+5' },
  { name: 'Armadura de angel caido', attributes: 'armadura+22, nulimagia+22' },
  { name: 'espada de angel caido', attributes: 'ataque+1d13' },
  { name: 'escudo de angel caido', attributes: 'defensa+1d10' },
  { name: 'casco de angel caido', attributes: 'armadura+8, nulimagia+8' },
  { name: 'guanteletes de angel caido', attributes: 'armadura+8, nulimagia+8' },
  { name: 'botas de angel caido', attributes: 'armadura+8, nulimagia+8' },
  { name: 'capa de angel caido', attributes: 'armadura+6, nulimagia+8, mana+2' },
  { name: 'cetro de angel caido', attributes: 'ataque_magico+1d10, mana+6' },
  // Items 201-280
  { name: 'armadura de abad', attributes: 'armadura+15, nulimagia+20' },
  { name: 'cetro de abad', attributes: 'ataque_magico+1d8, mana+8' },
  { name: 'Armadura de acolito', attributes: 'armadura+10, nulimagia+15, mana+2' },
  { name: 'cetro de acolito', attributes: 'ataque_magico+1d6, mana+6' },
  { name: 'Armadura de acolito corrupto', attributes: 'armadura+12, nulimagia+12, mana+2' },
  { name: 'cetro acolito corrupto', attributes: 'ataque_magico+1d7, mana+5' },
  { name: 'armadura de acolito de la muerte', attributes: 'armadura+18, nulimagia+18, mana+4' },
  { name: 'cetro de acolito de la muerte', attributes: 'ataque_magico+1d9, mana+8' },
  { name: 'armadura de bruja', attributes: 'armadura+12, nulimagia+15, mana+4' },
  { name: 'cetro de bruja', attributes: 'ataque_magico+1d8, mana+6' },
  { name: 'escoba de bruja', attributes: 'ataque_magico+1d6' },
  { name: 'armadura de nigromante', attributes: 'armadura+15, nulimagia+18, mana+5' },
  { name: 'cetro de nigromante', attributes: 'ataque_magico+1d9, mana+8' },
  { name: 'armadura de mago impuro', attributes: 'armadura+14, nulimagia+16, mana+4' },
  { name: 'cetro de mago impuro', attributes: 'ataque_magico+1d8, mana+7' },
  { name: 'Armadura de paladin', attributes: 'armadura+25, nulimagia+20' },
  { name: 'espada de paladin', attributes: 'ataque+1d11' },
  { name: 'escudo de paladin', attributes: 'defensa+1d10' },
  { name: 'Armadura de caballero', attributes: 'armadura+20, nulimagia+15' },
  { name: 'espada de caballero', attributes: 'ataque+1d10' },
  { name: 'escudo de caballero', attributes: 'defensa+1d8' },
  { name: 'armadura de caballero oscuro', attributes: 'armadura+22, nulimagia+18' },
  { name: 'espada de caballero oscuro', attributes: 'ataque+1d11' },
  { name: 'escudo de caballero oscuro', attributes: 'defensa+1d9' },
  { name: 'Armadura de caballero dragon', attributes: 'armadura+30, nulimagia+22' },
  { name: 'espada de caballero dragon', attributes: 'ataque+1d13' },
  { name: 'escudo de caballero dragon', attributes: 'defensa+1d11' },
  { name: 'Armadura de caballero de la muerte', attributes: 'armadura+28, nulimagia+25' },
  { name: 'espada de caballero de la muerte', attributes: 'ataque+1d12' },
  { name: 'escudo de caballero de la muerte', attributes: 'defensa+1d10' },
  { name: 'armadura de general', attributes: 'armadura+25, nulimagia+18' },
  { name: 'espada de general', attributes: 'ataque+1d12' },
  { name: 'Armadura de gladiador', attributes: 'armadura+18, nulimagia+12' },
  { name: 'espada de gladiador', attributes: 'ataque+1d10' },
  { name: 'escudo de gladiador', attributes: 'defensa+1d8' },
  { name: 'redonda de caballero', attributes: 'defensa+1d6' },
  { name: 'escudo cometa', attributes: 'defensa+1d8' },
  { name: 'escudo de cuero', attributes: 'defensa+1d4' },
  { name: 'escudo de hierro', attributes: 'defensa+1d6' },
  { name: 'escudo de acero redondo', attributes: 'defensa+1d8' },
  { name: 'escudo torre de acero', attributes: 'defensa+1d10' },
  { name: 'escudo de caballero', attributes: 'defensa+1d7' },
  { name: 'escudo de plata', attributes: 'defensa+1d7' },
  { name: 'Petra Genitalis', attributes: 'ataque+1d10' },
  { name: 'cetro de cuarzo', attributes: 'ataque_magico+1d5, mana+4' },
  { name: 'cetro de citrino', attributes: 'ataque_magico+1d6, mana+5' },
  { name: 'cetro de amatista', attributes: 'ataque_magico+1d7, mana+6' },
  { name: 'cetro de zafiro', attributes: 'ataque_magico+1d8, mana+7' },
  { name: 'cetro de rubi', attributes: 'ataque_magico+1d9, mana+8' },
  { name: 'cetro de esmeralda', attributes: 'ataque_magico+1d10, mana+9' },
  // Items 281-330
  { name: 'cetro de diamante', attributes: 'ataque_magico+1d11, mana+10' },
  { name: 'cetro de la reyna', attributes: 'ataque_magico+1d12, mana+12' },
  { name: 'cetro del sol', attributes: 'ataque_magico+1d11, mana+10' },
  { name: 'cetro de la luna', attributes: 'ataque_magico+1d11, mana+10' },
  { name: 'cetro de las estrellas', attributes: 'ataque_magico+1d12, mana+12' },
  { name: 'cetro del caos', attributes: 'ataque_magico+1d12, mana+10' },
  { name: 'cetro de la muerte', attributes: 'ataque_magico+1d10, mana+8' },
  { name: 'cetro de la vida', attributes: 'ataque_magico+1d8, mana+10' },
  { name: 'cetro de la naturaleza', attributes: 'ataque_magico+1d9, mana+8' },
  { name: 'daga de mana', attributes: 'ataque+1d2' },
  { name: 'daga del erudito', attributes: 'ataque+1d2' },
  { name: 'daga imbuida', attributes: 'ataque+1d2' },
  { name: 'anillo de proteccion', attributes: 'armadura+2, nulimagia+2' },
  { name: 'anillo de fuerza', attributes: 'ataque+2' },
  { name: 'anillo de agilidad', attributes: 'agilidad+2' },
  { name: 'anillo de la naturaleza', attributes: 'mana+3' },
  { name: 'anillo de fuego', attributes: 'ataque_magico+2' },
  { name: 'anillo de hielo', attributes: 'armadura+2, nulimagia+2' },
  { name: 'anillo de la tormenta', attributes: 'ataque+1, ataque_magico+1' },
  { name: 'amuleto de proteccion', attributes: 'armadura+3, nulimagia+3' },
  { name: 'amuleto de fuerza', attributes: 'ataque+3' },
  { name: 'amuleto de agilidad', attributes: 'agilidad+3' },
  { name: 'amuleto de la naturaleza', attributes: 'mana+4' },
  { name: 'amuleto de fuego', attributes: 'ataque_magico+3' },
  { name: 'amuleto de hielo', attributes: 'armadura+3, nulimagia+3' },
  { name: 'capa de fuerza', attributes: 'ataque+2' },
  { name: 'capa de proteccion', attributes: 'armadura+2, nulimagia+2' },
  { name: 'capa de agilidad', attributes: 'agilidad+2' },
  { name: 'capa del heroe', attributes: 'armadura+5, nulimagia+5' },
  { name: 'capa del dragon', attributes: 'armadura+4, nulimagia+6' },
  { name: 'capa del guardian', attributes: 'armadura+6, nulimagia+4' },
  { name: 'capa del mago', attributes: 'armadura+3, nulimagia+5, mana+2' },
  { name: 'capa del asesino', attributes: 'armadura+3, nulimagia+3' },
  { name: 'capa del cazador', attributes: 'armadura+3, nulimagia+3' },
  { name: 'capa del guerrero', attributes: 'armadura+4, nulimagia+2' },
  { name: 'capa de la reyna', attributes: 'armadura+6, nulimagia+8, mana+3' },
  { name: 'armadura del heroe', attributes: 'armadura+22, nulimagia+18' },
  { name: 'espada del heroe', attributes: 'ataque+1d12' },
  { name: 'escudo del heroe', attributes: 'defensa+1d10' },
  { name: 'casco del heroe', attributes: 'armadura+8, nulimagia+6' },
  // Items 331-400
  { name: 'guanteletes del heroe', attributes: 'armadura+8, nulimagia+6' },
  { name: 'botas del heroe', attributes: 'armadura+8, nulimagia+6' },
  { name: 'armadura del dragon legendario', attributes: 'armadura+45, nulimagia+35' },
  { name: 'espada del dragon legendario', attributes: 'ataque+1d18' },
  { name: 'escudo del dragon legendario', attributes: 'defensa+1d16' },
  { name: 'casco del dragon legendario', attributes: 'armadura+12, nulimagia+10' },
  { name: 'guanteletes del dragon legendario', attributes: 'armadura+12, nulimagia+10' },
  { name: 'botas del dragon legendario', attributes: 'armadura+12, nulimagia+10' },
  { name: 'armadura del angel supremo', attributes: 'armadura+35, nulimagia+40, mana+8' },
  { name: 'espada del angel supremo', attributes: 'ataque+1d15' },
  { name: 'escudo del angel supremo', attributes: 'defensa+1d12' },
  { name: 'casco del angel supremo', attributes: 'armadura+10, nulimagia+12, mana+4' },
  { name: 'guanteletes del angel supremo', attributes: 'armadura+10, nulimagia+12, mana+4' },
  { name: 'botas del angel supremo', attributes: 'armadura+10, nulimagia+12, mana+4' },
  { name: 'capa del angel supremo', attributes: 'armadura+8, nulimagia+12, mana+6' },
  { name: 'armadura del demonio supremo', attributes: 'armadura+38, nulimagia+32' },
  { name: 'espada del demonio supremo', attributes: 'ataque+1d16' },
  { name: 'escudo del demonio supremo', attributes: 'defensa+1d12' },
  { name: 'casco del demonio supremo', attributes: 'armadura+10, nulimagia+10' },
  { name: 'guanteletes del demonio supremo', attributes: 'armadura+10, nulimagia+10' },
  { name: 'botas del demonio supremo', attributes: 'armadura+10, nulimagia+10' },
  { name: 'capa del demonio supremo', attributes: 'armadura+8, nulimagia+10, mana+3' },
  { name: 'Armadura del vacio', attributes: 'armadura+50, nulimagia+45' },
  { name: 'Espada del vacio', attributes: 'ataque+1d20' },
  { name: 'Escudo del vacio', attributes: 'defensa+1d16' },
  { name: 'Yelmo del vacio', attributes: 'armadura+14, nulimagia+12' },
  { name: 'Guanteletes del vacio', attributes: 'armadura+14, nulimagia+12' },
  { name: 'Grebas del vacio', attributes: 'armadura+14, nulimagia+12' },
  { name: 'Capa del vacio', attributes: 'armadura+10, nulimagia+14, mana+5' },
  { name: 'armadura ligera de cuero', attributes: 'armadura+4, nulimagia+3' },
  { name: 'pantalones de cuero', attributes: 'armadura+3, nulimagia+2' },
  { name: 'botas de cuero', attributes: 'armadura+3, nulimagia+2' },
  { name: 'guantes de cuero', attributes: 'armadura+3, nulimagia+2' },
  { name: 'casco ligero de cuero', attributes: 'armadura+3, nulimagia+2' },
  { name: 'armadura de caza', attributes: 'armadura+8, nulimagia+6' },
  { name: 'botas de caza', attributes: 'armadura+3, nulimagia+2' },
  { name: 'guantes de caza', attributes: 'armadura+3, nulimagia+2' },
  { name: 'casco de caza', attributes: 'armadura+3, nulimagia+2' },
  { name: 'capa de caza', attributes: 'armadura+2, nulimagia+3' },
  { name: 'peto de caza', attributes: 'armadura+5, nulimagia+4' },
  // Items 401-480
  { name: 'armadura de asalto', attributes: 'armadura+15, nulimagia+10' },
  { name: 'casco de asalto', attributes: 'armadura+6, nulimagia+4' },
  { name: 'botas de asalto', attributes: 'armadura+6, nulimagia+4' },
  { name: 'guantes de asalto', attributes: 'armadura+6, nulimagia+4' },
  { name: 'capa de asalto', attributes: 'armadura+5, nulimagia+4' },
  { name: 'armadura del guardian', attributes: 'armadura+20, nulimagia+15' },
  { name: 'casco del guardian', attributes: 'armadura+8, nulimagia+6' },
  { name: 'botas del guardian', attributes: 'armadura+8, nulimagia+6' },
  { name: 'guantes del guardian', attributes: 'armadura+8, nulimagia+6' },
  { name: 'capa del guardian', attributes: 'armadura+6, nulimagia+6' },
  { name: 'coraza de placas', attributes: 'armadura+14, nulimagia+10' },
  { name: 'casco de placas', attributes: 'armadura+7, nulimagia+5' },
  { name: 'botas de placas', attributes: 'armadura+7, nulimagia+5' },
  { name: 'guanteletes de placas', attributes: 'armadura+7, nulimagia+5' },
  { name: 'espada de placas', attributes: 'ataque+1d9' },
  { name: 'Arco de placas', attributes: 'ataque+1d9' },
  { name: 'armadura del dragon de escarcha', attributes: 'armadura+40, nulimagia+30' },
  { name: 'espada del dragon de escarcha', attributes: 'ataque+1d15' },
  { name: 'escudo del dragon de escarcha', attributes: 'defensa+1d13' },
  { name: 'casco del dragon de escarcha', attributes: 'armadura+12, nulimagia+10' },
  { name: 'guanteletes del dragon de escarcha', attributes: 'armadura+12, nulimagia+10' },
  { name: 'botas del dragon de escarcha', attributes: 'armadura+12, nulimagia+10' },
  { name: 'capa del dragon de escarcha', attributes: 'armadura+8, nulimagia+10, mana+3' },
  { name: 'armadura del dragon abisal', attributes: 'armadura+48, nulimagia+40' },
  { name: 'espada del dragon abisal', attributes: 'ataque+1d18' },
  { name: 'escudo del dragon abisal', attributes: 'defensa+1d15' },
  { name: 'casco del dragon abisal', attributes: 'armadura+14, nulimagia+12' },
  { name: 'guanteletes del dragon abisal', attributes: 'armadura+14, nulimagia+12' },
  { name: 'botas del dragon abisal', attributes: 'armadura+14, nulimagia+12' },
  { name: 'capa del dragon abisal', attributes: 'armadura+10, nulimagia+12, mana+4' },
  { name: 'armadura del dios de la guerra', attributes: 'armadura+55, nulimagia+45' },
  { name: 'espada del dios de la guerra', attributes: 'ataque+1d22' },
  { name: 'escudo del dios de la guerra', attributes: 'defensa+1d18' },
  { name: 'casco del dios de la guerra', attributes: 'armadura+16, nulimagia+14' },
  { name: 'guanteletes del dios de la guerra', attributes: 'armadura+16, nulimagia+14' },
  { name: 'botas del dios de la guerra', attributes: 'armadura+16, nulimagia+14' },
  { name: 'capa del dios de la guerra', attributes: 'armadura+12, nulimagia+14, mana+5' },
  // Items 481-530
  { name: 'lanza sangrienta despertada', attributes: 'ataque+1d8' },
  { name: 'revolver', attributes: 'ataque+1d6' },
  { name: 'revolver cazador', attributes: 'ataque+1d11' },
  { name: 'revolver gran calibre', attributes: 'ataque+1d10' },
  { name: 'revolver maldito', attributes: 'ataque+1d11' },
  { name: 'sombrero magico', attributes: 'armadura+3, nulimagia+2, mana+2' },
  { name: 'sombrero sacerdote', attributes: 'armadura+6, nulimagia+6' },
  { name: 'rifle alta precision', attributes: 'ataque+2d20' },
  { name: 'rifle', attributes: 'ataque+2d11' },
  { name: 'gorrocoptero', attributes: 'armadura+7' },
  { name: 'gran escudo hierro', attributes: 'defensa+1d15' },
  { name: 'guanteletes coral', attributes: 'armadura+6, nulimagia+5' },
  { name: 'gran hacha de guerra', attributes: 'ataque+2d9' },
  { name: 'gran mazo', attributes: 'ataque+2d7' },
  { name: 'botas cuero', attributes: 'armadura+3' },
  { name: 'guadaña del bufon', attributes: 'ataque+1d10' },
  { name: 'guantelete del infinito', attributes: 'armadura+7' },
  { name: 'guanteletes arcanos', attributes: 'armadura+6, nulimagia+6, mana+2' },
  { name: 'guanteletes obsidiana', attributes: 'armadura+8, nulimagia+8, mana-4' },
  { name: 'guantes del guerrero', attributes: 'armadura+6, nulimagia+4, estamina+2' },
  { name: 'guanteletes de fundicion', attributes: 'ataque+4d4, armadura+3' },
  { name: 'guanteletes incendiados', attributes: 'ataque+2d5+1d4' },
  { name: 'botafumeiro divino', attributes: 'ataque+1d5' },
  { name: 'botas de entrenamiento', attributes: 'armadura+4, nulimagia+2, mana-2' },
  { name: 'botas elficas', attributes: 'armadura+5, nulimagia+3' },
  { name: 'botas obsidiana', attributes: 'armadura+10, nulimagia+7, mana-4' },
  { name: 'botas protectoras', attributes: 'armadura+8, nulimagia+6, mana-3, estamina-1' },
  { name: 'botas sagradas', attributes: 'armadura+6, nulimagia+5' },
  { name: 'casco runico', attributes: 'armadura+6, nulimagia+6, mana+1, estamina+1' },
  { name: 'capucha del asesino', attributes: 'armadura+5, nulimagia+5' },
  { name: 'casco cuero', attributes: 'armadura+3, nulimagia+1' },
  { name: 'casco dragon', attributes: 'armadura+14, mana+2, estamina+1' },
  // Items 531-580
  { name: 'casco valkiria', attributes: 'armadura+8, nulimagia+8' },
  { name: 'cerbatana', attributes: 'ataque+1' },
  { name: 'cetro de agua fluyente', attributes: 'ataque+1d10' },
  { name: 'pistola rapida', attributes: 'ataque+1d6' },
  { name: 'pistola ramus', attributes: 'ataque+1d8' },
  { name: 'cinturon negro', attributes: 'ataque+3d4' },
  { name: 'hacha calabaza', attributes: 'ataque+1d10' },
  { name: 'cetro del bosque', attributes: 'ataque+1d3, mana+7' },
  { name: 'katana filo acuatico', attributes: 'ataque+1d7, estamina-1' },
  { name: 'ballesta ejecutora', attributes: 'ataque+1d9' },
  { name: 'espada dragon', attributes: 'ataque+1d12' },
  { name: 'arco sagrado', attributes: 'ataque+5d4' },
  { name: 'arco natura', attributes: 'ataque+2d9+2' },
  { name: 'chakram pesado oscuro', attributes: 'ataque+2d8' },
  { name: 'katana resplandor blanco', attributes: 'ataque+1d7+1d5' },
  { name: 'armadura dragon', attributes: 'armadura+55, nulimagia+60' },
  { name: 'Mjolnir', attributes: 'ataque+1d12' },
  { name: 'armadura perfecta de hojas', attributes: 'armadura+45, nulimagia+43, mana+5' },
  { name: 'armadura de la torre', attributes: 'armadura+60, nulimagia+55' },
  { name: 'corona de critias', attributes: 'armadura+10, nulimagia+6, estamina+1, mana+2' },
  { name: 'chakram valkiria', attributes: 'ataque+1d10' },
  { name: 'corona carmesi', attributes: 'armadura+6, nulimagia+4' },
  { name: 'cetro solar', attributes: 'ataque+1d9, mana+1' },
  { name: 'lanza sangrienta', attributes: 'ataque+1d7' },
  { name: 'casco de huesos', attributes: 'armadura+12, nulimagia+10, defensa+1d2, estamina+1' },
  { name: 'alma corrupta', attributes: 'ataque+1d7, estamina+1' },
  { name: 'corona de timaeus', attributes: 'armadura+10, nulimagia+6, mana+4' },
  { name: 'chakram electrico', attributes: 'ataque+1d10' },
  { name: 'lanza del necromancer', attributes: 'ataque+1d8' },
  { name: 'cetro lunar', attributes: 'ataque+1d9, mana+2' },
  // Items 581-630
  { name: 'arcoescudo', attributes: 'ataque+2d7+2, defensa+1d14' },
  { name: 'katana ardiente', attributes: 'ataque+2d5+1d4' },
  { name: 'estoque lujurioso', attributes: 'ataque+6d1' },
  { name: 'botas tiburon', attributes: 'armadura+5, nulimagia+4' },
  { name: 'cetro de hermes', attributes: 'ataque+1' },
  { name: 'escudo dark hole', attributes: 'defensa+1d7' },
  { name: 'capucha elemental oscura', attributes: 'armadura+7, nulimagia+5, mana+3' },
  { name: 'Colgante de Escamas Gélidas', attributes: 'mana+2' },
  { name: 'daga del fin', attributes: 'ataque+1d4' },
  { name: 'Anillo del Dragón de Hielo', attributes: 'estamina+1' },
  { name: 'hacha demoniaca', attributes: 'ataque+1d8' },
  { name: 'revolver oscuro', attributes: 'ataque+1d13' },
  { name: 'ballesta maldita', attributes: 'ataque+1d13' },
  { name: 'ballesta de la ira', attributes: 'ataque+1d9' },
  { name: 'ballesta volcanica', attributes: 'ataque+1d11' },
  { name: 'ballesta cosmica', attributes: 'ataque+1d12' },
  { name: 'lanza angelical', attributes: 'ataque+2d8+2' },
  { name: 'ballesta de la humildad', attributes: 'ataque+1d12' },
  { name: 'cinturon torrencial', attributes: 'ataque+3d6+2' },
  { name: 'Katana de sangre', attributes: 'ataque+3d5+3' },
  { name: 'guanteletes de combate', attributes: 'ataque+3d4+2' },
  { name: 'katana fuego del sur', attributes: 'ataque+2d5+1d4+2' },
  { name: 'mascara del ciclo', attributes: 'armadura+4, nulimagia+4, mana+2' },
  { name: 'escudo corazon de puas', attributes: 'defensa+1d5+1d4' },
  { name: 'tunica runica', attributes: 'armadura+18, nulimagia+20, mana+5, estamina-6' },
  { name: 'cetro sangriento', attributes: 'ataque+1d9' },
  { name: 'espada nigromante', attributes: 'ataque+1d11' },
  { name: 'armadura del caballero muerto', attributes: 'armadura+32, nulimagia+32, vida+12' },
  { name: 'armadura del caballero muerto definitiva', attributes: 'armadura+38, nulimagia+38, vida+12' },
  { name: 'Guantes de Fenrir', attributes: 'ataque+3d6' },
  // Items 631-680
  { name: 'Vertebra Silente', attributes: 'ataque+1d7' },
  { name: 'Columna de los Errantes', attributes: 'ataque+1d12+1d10+2' },
  { name: 'Guantes de excavacion', attributes: 'ataque+2d7' },
  { name: 'cinturon dragon', attributes: 'ataque+2d9+1' },
  { name: 'coraza samurai', attributes: 'armadura+18, nulimagia+13, mana-1' },
  { name: 'oscuridad alternante', attributes: 'ataque+1d22, defensa+1d8+1d5' },
  { name: 'coraza samurai legendario', attributes: 'armadura+23, nulimagia+17, estamina+1, mana-3' },
  { name: 'hacha fundida', attributes: 'ataque+2d8+2' },
  { name: 'Azote de Mundos', attributes: 'ataque+2d10+1dX' },
  { name: 'rifle arcano', attributes: 'ataque+2d10+2' },
  { name: 'coraza canalizadora desatada', attributes: 'armadura+26, nulimagia+24, mana+2, estamina-4' },
  { name: 'mazo reloj de arena', attributes: 'ataque+1d12' },
  { name: 'espada piedra', attributes: 'ataque+1d8' },
  { name: 'Encierro del Laberinto', attributes: 'armadura+52, nulimagia+52' },
  { name: 'Justicia de los Cielos', attributes: 'ataque+1d10' },
  { name: 'katana lunar', attributes: 'ataque+2d5+1d4+2' },
  { name: 'katana viento del norte', attributes: 'ataque+3d5+2' },
  { name: 'escudo impenetrable', attributes: 'defensa+3d6' },
  { name: 'escudo lobo corrupto', attributes: 'defensa+2d6+1d4' },
  { name: 'guantes filo bestial', attributes: 'armadura+4, nulimagia+2' },
  { name: 'katana solar', attributes: 'ataque+2d5+1d4+2' },
  { name: 'escudo guardian de la torre', attributes: 'defensa+2d6+1d4' },
  { name: 'espada cero absoluto', attributes: 'ataque+1d12' },
  { name: 'espadon invierno eterno', attributes: 'ataque+2d9+2' },
  { name: 'guanteletes toxicos', attributes: 'ataque+2d6+1d4' },
  { name: 'guantes de huesos', attributes: 'ataque+3d6' },
  { name: 'vendas de combate', attributes: 'ataque+2d9' },
  { name: 'Corazon del Necromancer', attributes: 'vida-5' },
  { name: 'guantes ladronzuelo', attributes: 'armadura+1, nulimagia+1' },
  { name: 'chakram divino', attributes: 'ataque+2d9+2' },
  // Items 681-720
  { name: 'escudo templario iluminado', attributes: 'defensa+1d5+1d6' },
  { name: 'Vinculo de Sangre', attributes: 'ataque+1d10' },
  { name: 'La legendaria Espada Z', attributes: 'ataque+3d4' },
  { name: 'Rakanishu', attributes: 'ataque+1d12' },
  { name: 'Rugidos de Gilneas', attributes: 'ataque+2d8+3' },
  { name: 'Paraguas Rosado', attributes: 'ataque+1d13' },
  { name: 'Lanza Reloj de los Cielos', attributes: 'ataque+1d13' },
  { name: 'Cetro de Suris', attributes: 'ataque+1d4, mana+8' },
  { name: 'Mandoble Le Warden', attributes: 'ataque+2d10+2' },
  { name: 'Caelumbra', attributes: 'ataque+1d11' },
  { name: 'Black Knife', attributes: 'ataque+1d12' },
  { name: 'Filo Segador', attributes: 'ataque+2d5+1d7+2' },
  { name: 'armadura lider suprema', attributes: 'armadura+55, nulimagia+55, mana+10' },
  { name: 'Espada Omnielemental', attributes: 'ataque+1d12' },
  { name: 'Miff & Sha', attributes: 'ataque+2d7+2, defensa+2d7+2' },
  { name: 'Taurvanya', attributes: 'defensa+1d7+1d6' },
  { name: 'Corazon del Bosque', attributes: 'vida+20' },
  { name: 'chakram volcanico', attributes: 'ataque+1d11' },
  { name: 'escudo dragon dorado', attributes: 'defensa+1d11' },
  { name: 'escudo reflectante', attributes: 'defensa+1d11' },
  { name: 'escudo espartano', attributes: 'defensa+1d6' },
  { name: 'escudo conchas', attributes: 'defensa+1d6' },
  { name: 'escudo templario profanado', attributes: 'defensa+1d10' },
  { name: 'escudo diamante', attributes: 'defensa+2d4+1d3' },
  { name: 'escudo archimagico', attributes: 'defensa+1d11, mana+2' },
  { name: 'escudo demoniaco', attributes: 'defensa+1d5+1d6' },
  { name: 'escudo maligno', attributes: 'defensa+1d10, ataque+2' },
  { name: 'escudo del devorador', attributes: 'defensa+1d6+1d5' },
  { name: 'escudo del valhalla', attributes: 'defensa+1d6+1d5' },
  { name: 'Cadenas de Lealtad', attributes: 'ataque+3d6' },
  { name: 'Skadian Gamblign Sword', attributes: 'ataque+1d12' },
  { name: 'Cetro del Fruto', attributes: 'ataque+1d4, mana+12' },
  { name: 'Sharœra', attributes: 'ataque+1d12' },
  { name: 'pecera', attributes: 'armadura+4, nulimagia+4' },
  { name: 'casco de buzo', attributes: 'armadura+6, nulimagia+6' },
  { name: 'mazo de la creacion', attributes: 'ataque+1d11' },
]

export function applyItemReview(db: Database.Database): void {
  const hasReview = db.prepare("SELECT name FROM data_migration WHERE name = 'item_review_v1'").get()
  if (hasReview) return

  const getId = db.prepare('SELECT id FROM items WHERE name = ?')
  const isIngredient = db.prepare('SELECT COUNT(*) as count FROM recipe_ingredients WHERE item_id = ?')
  const isProduct = db.prepare('SELECT COUNT(*) as count FROM recipes WHERE product_item_id = ?')
  const delCharItems = db.prepare('DELETE FROM character_items WHERE item_id = ?')
  const delItemTags = db.prepare('DELETE FROM item_tags WHERE item_id = ?')
  const delRecipeIng = db.prepare('DELETE FROM recipe_ingredients WHERE recipe_id IN (SELECT id FROM recipes WHERE product_item_id = ?)')
  const delRecipes = db.prepare('DELETE FROM recipes WHERE product_item_id = ?')
  const delItem = db.prepare('DELETE FROM items WHERE id = ?')
  const updateItem = db.prepare('UPDATE items SET attributes = ? WHERE name = ?')

  const tx = db.transaction(() => {
    let deleted = 0
    let updated = 0
    let skipped = 0

    for (const item of itemsToDelete) {
      const row = getId.get(item.name) as { id: number } | undefined
      if (!row) continue
      const ingCount = (isIngredient.get(row.id) as { count: number }).count
      const prodCount = (isProduct.get(row.id) as { count: number }).count
      if (ingCount > 0 || prodCount > 0) {
        console.log(`Skipping deletion of "${item.name}" — used in ${prodCount > 0 ? 'recipes as product' : ''}${prodCount > 0 && ingCount > 0 ? ' and ' : ''}${ingCount > 0 ? 'recipes as ingredient' : ''}`)
        skipped++
        continue
      }
      delCharItems.run(row.id)
      delItemTags.run(row.id)
      delRecipeIng.run(row.id)
      delRecipes.run(row.id)
      const result = delItem.run(row.id)
      if (result.changes > 0) deleted++
    }
    if (skipped > 0) console.log(`Skipped ${skipped} items that are referenced in recipes`)

    for (const item of itemsToUpdate) {
      const result = updateItem.run(item.attributes, item.name)
      if (result.changes > 0) updated++
    }

    db.prepare("INSERT INTO data_migration (name, time_completed) VALUES ('item_review_v1', strftime('%s','now') * 1000)").run()

    console.log(`Item review applied: ${deleted} deleted, ${updated} updated`)
  })
  tx()
}
